embedding_model_name: "sentence-transformers/msmarco-distilbert-base-v4"
top_k: 3

raw_docs_path: "data/raw"  # "/vol/fob-vol5/mi22/koenigfd/data/raw/raw"  #

arxiv_download:
  categories:
    - "cs.CL"
  year: 2025
  month: 6

FAISS:
  index_path: "data/faiss_index"  # "/vol/fob-vol5/mi22/koenigfd/data/faiss_index"
  metadata_path: "data/faiss_metadata.pkl"  # "/vol/fob-vol5/mi22/koenigfd/data/faiss_metadata.pkl"

RAG:
  chunk_size: 700
  chunk_overlap: 100
  batch_size: 4096 * 2  # Adjust to memory limits

gradio_server:
  host: "0.0.0.0"    # or "127.0.0.1" for local only
  port: 7860
