[project]
name = "insight-bridge"
version = "0.1.0"
description = ""
authors = [
    {name = "Ferdinand Koenig",email = "ferdinand@koenix.de"}
]
license = {text = "CC BY-NC-SA 4.0"}
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
